### ISSUE TITLE
Asessment 2

### ISSUE THREAD

**Issue by rizzamandasari** [martinrahmanhakim/to-do-apps-v2-assessment2-mopro1#1]
Aplikasi berjalan dengan baik, namun:
1. Ada fitur-fitur dari assessment 1 hilang, spt perubahan bahasa.
2. Lazimnya saaat berpindah antara satu aktivity ke activity lain biasanya menggunakan button biasa bukan FAB. 😄

**Comment by martinrahmanhakim** [comment]
Permisi, ibu.
Aplikasi Assessment 2 saya sudah diperbaiki sesuai dengan point yang ibu berikan.
Untuk file aplikasi (.apk) sudah diupload di Google Drive Assessment 2 saya.
Berikut bukti upload di Google Drive yang bernama "**app-debug-revisi-ass2.apk**" dan Link Google Drive Assessment 2:

https://drive.google.com/drive/folders/1SEpGU1t_j7fZiwE_4F8ZoWRy6fHp7J40?usp=drive_link

<img width="1680" alt="Screenshot 2024-06-24 at 18 11 07" src="https://github.com/martinrahmanhakim/to-do-apps-v2-assessment2-mopro1/assets/114900203/6ba21408-d93f-4669-a59f-aa26c9046fbe">

Dan terlampir untuk bukti perbaikan saat perpindahan satu activity menggunkan button biasa ("Get Started"):

![WhatsApp Image 2024-06-24 at 15 55 45](https://github.com/martinrahmanhakim/to-do-apps-v2-assessment2-mopro1/assets/114900203/e9e21fbe-ba20-48df-898f-7b957726bbe5)

**Comment by rizzamandasari** [comment]
OK. Close
